### ISSUE TITLE
Crash when attempting to use with Mekanism Tools and Generators...

### ISSUE THREAD

**Issue by ate0ate** [dizzyd/Mekanism#1]
I can't seem to start my custom pack when using your fork due to Mek Generators and Mek Tools depending specifically on the current build of Aidan's Mekanism. Is there an easy way around this so I can still use Generators and Tools?

**Comment by jburrows82** [comment]
Generators & Tools depend on the same matching version of the base mod instead of a minimum, so unfortunately the addons don't work with your fork. Isn't there a build flag for development versions to build an all in one package? Even though you haven't touched the addons, that would help anyone wanting to use your fork (which thank you btw, despite the curse nazis accusing you of point leeching).

If you don't want to do the AIO solution, would you at least publish a fork of the addons too that allow a minimum version or higher please?

**Comment by ate0ate** [comment]
Looks like he has everything all set nicely already, he just uploaded only the base mod. I compiled his source and it has the usual Base, Generators and Tools as well as the "All" combined version of the three mods. They work wonderfully. I just decided to go with the combined jar so I only have one mod to deal with rather than three. Link to the compiled build/libs folder here... 
http://www.mediafire.com/folder/7dc8qcqf02e7g/libs

**Comment by dizzyd** [comment]
I've created projects for [Tools](https://minecraft.curseforge.com/projects/mekanism-tools-dz-edition) and [Generators](https://minecraft.curseforge.com/projects/mekanism-generators-dz-edition) and rebuilt 9.4.14 - once the files are approved, we should be good to go.

I'll close this issue in the morning once I've validated the new files/projects are working.

**Comment by ate0ate** [comment]
Sounds good to me. Thank you very much for your efforts here. Its nice to see Mekanism get some much needed love :)

**Comment by dizzyd** [comment]
New projects are up and available. :)
