### ISSUE TITLE
Add compatibility for Super Sound Muffler (and/or similar mods and blocks)

### ISSUE THREAD

**Issue by GreatestFool** [dizzyd/Mekanism#15]
This has been an issue ever since Mekanism switched to their custom sound system, I don't _really_ mind the sound, there are the upgrades. I just find the fact that the only other way than those is to turn down, or even off, the entire thing.

If it isn't too bothersome for you, can you add compatibility somewhere down the line?

**Comment by pupnewfster** [comment]
Mekanism works with the super sound muffler though? It doesn't work with sound mufflers from other mods though if memory serves.

**Comment by GreatestFool** [comment]
When I tried about a three weeks or one month ago, it did not work. Searched a little, and it is apparently a known thing.

**Comment by pupnewfster** [comment]
I know that I use them together and it works just fine. A few things to note, it won't stop in progress sounds, so you have to stop the Mekanism machine before it will start blocking it. And secondly I use the mode where I blacklist sounds and manually blacklist the mekanism machines. (Not sure if that makes a difference)

**Comment by dizzyd** [comment]
FWIW, I've spent most of the day overhauling the sound system. It turned into an all-day hackfest and will probably take me a few days to validate. The good news is that it will now comply fully with the MC sounds system, so mufflers SHOULD work reliably since it's using vanilla semantics. Additional upsides are that I've trimmed out a few hundred (!!) lines of code and reduced the number of allocations from 1 per sound event to 1 per player (which on a running server will be significant). Also, you should be able to mute while a machine is running. :)

If anyone is interested in helping me test, drop me a line at my github nick @ my github nick.com.
