### ISSUE TITLE
Small Suggestion: Change fuel duration time of Charcoal Block

### ISSUE THREAD

**Issue by ate0ate** [dizzyd/Mekanism#8]
Just a small nitpick really, but Mekanism's charcoal block's burn time is oddly different than every other mod that adds a charcoal block. Mekanism has it set to a rate of 14400 ticks while everything else (Forestry, Thermal Expansion, Tiny Progressions, Quark, Actually Additions, etc...) has it set to be the more sensible rate of 16000 ticks.

**Comment by dizzyd** [comment]
Hi @ate0ate - I did some research on this. As it turns out, Mek is the more sensible default (IMO, of course) since the 14400 ticks is 9 times the standard burn time of an individual piece of charcoal/coal (1600). However, the MC source sets coal block to 16000 (i.e. 10 * 1600), so that's why everyone else does too.

At any rate, this will be fixed in 9.4.18 tomorrow sometime. :) Thanks!

**Comment by ate0ate** [comment]
That makes a lot of sense really. Your point about the value of individual coal/charcoal burn time got me thinking... 
I've been playing Mekanism for quite a long time now and I'm pretty sure the Charcoal Block was added to the mod either before the actual Block of Coal even existed in Vanilla Minecraft or right around it's debut in the April Fool's Day prank "Mincecraft 2.0." If I recall correctly, Dinnerbone had mentioned that the Block of Coal wouldn't actually make it into Vanilla due to a necessary Block of Charcoal needing to be created as well. I guess that was where Aidan got the idea lol. Either way, the Block of Coal actually had a burn time of 720 seconds before Mojang increased it later on to the current 800 seconds. I'm not sure why they increased it really, just as you said, but I suppose Aidan simply never thought to change the Charcoal Block to match it. 
Anyways, thanks for the input, and a bigger thank you for giving the mod some much needed attention!
